# Generated by Django 2.0.2 on 2018-04-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacherID',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='studentID',
        ),
    ]
