# Generated by Django 2.0.3 on 2018-04-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20180405_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equiptment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
