# Generated by Django 2.0.4 on 2018-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_time', models.DateTimeField(verbose_name='Lesson Time')),
                ('lesson_duration', models.CharField(choices=[('30', '30 Minutes'), ('60', '1 Hour'), ('90', '1.5 Hours'), ('120', '2 Hours')], default='60', max_length=3)),
                ('lesson_location', models.CharField(choices=[('A0', 'Room A0'), ('A1', 'Room A1'), ('A2', 'Room A2'), ('A3', 'Room A3'), ('A4', 'Room A4')], default='A0', max_length=2)),
            ],
        ),
    ]
