# Generated by Django 2.0.5 on 2018-05-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_auto_20180515_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateTimeField(verbose_name='Due Back')),
                ('instrument', models.CharField(choices=[('1', 'Guitar'), ('2', 'Drums'), ('3', 'Violin'), ('4', 'Saxophone'), ('5', 'Clarinet'), ('6', 'Piano'), ('7', 'Vocals'), ('8', 'Cello')], default='1', max_length=3)),
                ('instrument_condition', models.CharField(choices=[('1', 'Excellent'), ('2', 'Great'), ('3', 'Good'), ('4', 'Poor'), ('5', 'Broken')], default='1', max_length=2)),
                ('loan_student', models.ForeignKey(default=1, limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='loan_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
