# Generated by Django 2.0.5 on 2018-05-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessoninstrument', to='schedule.Inst'),
        ),
    ]
