# Generated by Django 2.0.5 on 2018-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_lesson_lesson_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst',
            name='instrument',
            field=models.CharField(choices=[('Guitar', 'Guitar'), ('Drums', 'Drums'), ('Violin', 'Violin'), ('Saxophone', 'Saxophone'), ('Clarinet', 'Clarinet'), ('Piano', 'Piano'), ('Vocals', 'Vocals'), ('Cello', 'Cello')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='inst',
            name='instrument_condition',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Excellent', 'Great'), ('Excellent', 'Good'), ('Excellent', 'Poor'), ('Excellent', 'Broken')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_instrument',
            field=models.CharField(choices=[('A0', 'Room A0'), ('A1', 'Room A1'), ('A2', 'Room A2'), ('A3', 'Room A3'), ('A4', 'Room A4')], default='1', max_length=20),
        ),
    ]
