# Generated by Django 2.0.5 on 2018-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20180529_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst',
            name='due_back',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Back'),
        ),
    ]
