# Generated by Django 2.0.4 on 2018-04-17 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_lesson_lesson_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_teacher',
            field=models.ForeignKey(default=0, limit_choices_to={'groups__name': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_student',
            field=models.ForeignKey(default=0, limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
