# Generated by Django 2.0.4 on 2018-05-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180417_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_time',
            field=models.DateTimeField(verbose_name='Lesson Time'),
        ),
    ]
