# Generated by Django 2.0.4 on 2018-04-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180417_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_field',
        ),
    ]
