# Generated by Django 2.0.4 on 2018-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180423_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_field',
        ),
        migrations.AddField(
            model_name='user',
            name='g_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='g_first_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='g_last_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='g_mobile_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('QLD', 'Queensland'), ('NSW', 'New South Wales'), ('ACT', 'ACT'), ('VIC', 'Victoria'), ('TAS', 'Tasmania'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('NT', 'Northern Territory')], default='QLD', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='street_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='street_number',
            field=models.BigIntegerField(default= 0),
        ),
        migrations.AddField(
            model_name='user',
            name='suburb',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='under_18',
            field=models.BooleanField(default='False'),
        ),
    ]
