# Generated by Django 2.0.4 on 2018-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180501_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='street_number',
            field=models.CharField(default='', max_length=4),
        ),
    ]
