# Generated by Django 2.0.4 on 2018-05-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180501_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='g_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='g_first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='g_last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='g_mobile_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='under_18',
        ),
    ]
