# Generated by Django 2.0.4 on 2018-05-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180501_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='g_first_name',
            new_name='guardian_first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='g_email',
            new_name='guardian_first_name_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='g_last_name',
            new_name='guardian_first_name_last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='g_mobile_number',
            new_name='guardian_first_name_mobile_number',
        ),
    ]
