# Generated by Django 2.0.4 on 2018-05-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180501_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='guardian_first_name_email',
            new_name='guardian_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='guardian_first_name_last_name',
            new_name='guardian_last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='guardian_first_name_mobile_number',
            new_name='guardian_mobile_number',
        ),
    ]
