# Generated by Django 2.0.4 on 2018-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180501_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guardian_email',
            field=models.EmailField(blank='True', default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_first_name',
            field=models.CharField(blank='True', default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_last_name',
            field=models.CharField(blank='True', default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_mobile_number',
            field=models.CharField(blank='True', default='', max_length=10),
        ),
    ]
