# Generated by Django 2.0.3 on 2018-04-18 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('studentID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstName', models.CharField(help_text='Enter your First Name Only', max_length=30)),
                ('lastName', models.CharField(help_text='Enter your Last Name Only', max_length=30)),
                ('DOB', models.DateField(help_text='Enter your Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstName', models.CharField(help_text='Enter your First Name Only', max_length=30)),
                ('lastName', models.CharField(help_text='Enter your Last Name Only', max_length=30)),
                ('skillsSummary', models.TextField(help_text='Provide a brief summary of your teaching skills and history', max_length=1000)),
            ],
        ),
    ]
