# Generated by Django 2.0.3 on 2018-04-18 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('instrumentID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instrument', models.CharField(help_text='Enter a name for the instrument', max_length=20)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Instrument availability', max_length=1)),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
